POST http://localhost:3000/user/add HTTP/1.1
Content-Type: application/json

{
    "firstname":"Karina",
    "lastname":"Aespa",
    "username":"karina",
    "password":"aespa",
    "birthdate":"1998-06-24T00:00:00Z",
    "position":"Artist"
}

###

GET http://localhost:3000/user/all HTTP/1.1
Content-Type: application/json

###

GET  http://localhost:3000/user/6046f4cb9dc7191424113bd2 HTTP/1.1
Content-Type: application/json

###

DELETE http://localhost:3000/user/delete/6048eda0b1b1af2aec06eac9 HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:3000/user/update/6048eda0b1b1af2aec06eac9 HTTP/1.1
Content-Type: application/json

{
   "password":"qwerty"
}