POST http://localhost:3000/user/add HTTP/1.1
Content-Type: application/json

{
    "firstname":"Raendy",
    "lastname":"Andhika",
    "username":"raendyandhika",
    "password":"andhika123.",
    "birthdate":"1998-06-24T00:00:00Z",
    "position":"Front End Developer"
}

###

GET http://localhost:3000/user/all HTTP/1.1
Content-Type: application/json

###

GET  http://localhost:3000/user/6046f4cb9dc7191424113bd2 HTTP/1.1
Content-Type: application/json

###

DELETE http://localhost:3000/user/delete/6046f7448a3a650bf8c16c36 HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:3000/user/update/6046f4cb9dc7191424113bd2 HTTP/1.1
Content-Type: application/json

{
   "username":"proxyhorse"
}